New upstream version 2.0.1

diff --git a/src/bin/keactrl/keactrl.in b/src/bin/keactrl/keactrl.in
--- a/src/bin/keactrl/keactrl.in
+++ b/src/bin/keactrl/keactrl.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2014-2019 Internet Systems Consortium, Inc. ("ISC")
+# Copyright (C) 2014-2021 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
@@ -10,9 +10,28 @@
 # This script is used to run Kea from installation directory,
 # as well as for running tests.
 
-VERSION=@PACKAGE_VERSION@
-@HAVE_SYSREPO_FALSE@have_netconf=0
-@HAVE_SYSREPO_TRUE@have_netconf=1
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, 'local' is undefined.
+
+# shellcheck disable=SC2154
+# SC2154: ... is referenced but not assigned.
+# Reason: some variables are taken from keactrl.conf
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+VERSION="@PACKAGE_VERSION@"
+
+# Set the have_netconf flag to know if netconf is available.
+if test -z '@HAVE_SYSREPO_TRUE@'; then
+    have_netconf=true
+else
+    have_netconf=false
+fi
 
 ### Logging functions ###
 
@@ -37,9 +56,9 @@ log_info() {
 # is to determine whether the keactrl command belongs to the list of
 # supported commands.
 is_in_list() {
-    local member=${1}  # Value to be checked
-    local list="${2}"  # Comma separated list of items
-    _inlist=0          # Return value: 0 if not in list, 1 otherwise.
+    local member="${1-}"  # Value to be checked
+    local list="${2-}"    # Comma separated list of items
+    _inlist=0             # Return value: 0 if not in list, 1 otherwise.
     if [ -z "${member}" ]; then
         log_error "missing ${member}"
     fi
@@ -74,7 +93,7 @@ usage() {
 #
 # shellcheck disable=SC2154
 get_pid_from_file() {
-    local proc_name=${1} # Process name.
+    local proc_name="${1}"  # Process name.
 
     local kea_config_file=
     case ${proc_name} in
@@ -95,16 +114,17 @@ get_pid_from_file() {
         ;;
     esac
 
-    # Extract the name portion of the config file
+    # Extract the name portion (from last slash to last dot) of the config file name
+    # File name and extension are documented in src/lib/util/filename.h
     local conf_name
-    conf_name=$(basename -- "${kea_config_file}" | cut -f1 -d'.')
+    conf_name=$(basename -- "${kea_config_file}" | rev | cut -f2- -d'.' | rev)
 
     # Default the directory to --localstatedir / run
     local pid_file_dir
-    pid_file_dir=@runstatedir@/@PACKAGE@
+    pid_file_dir="@runstatedir@/@PACKAGE@"
 
     # Use directory override if set (primarily for testing only)
-    if [ -n "$KEA_PIDFILE_DIR" ]; then
+    if test -n "${KEA_PIDFILE_DIR+x}"; then
         pid_file_dir=${KEA_PIDFILE_DIR}
     fi
 
@@ -112,13 +132,8 @@ get_pid_from_file() {
     _pid_file="${pid_file_dir}/${conf_name}.${proc_name}.pid"
 
     # Grab the PID if the file exists
-    if [ -e "${_pid_file}" ]; then
-        _pid=$(cat "${_pid_file}")
-        retcode=$?
-        if [ $retcode -ne 0 ]; then
-            log_error "Error reading PID file: ${_pid_file}"
-        fi
-    else
+    _pid=$(cat "${_pid_file}" 2> /dev/null || true)
+    if test -z "${_pid}"; then
         # No file, means no pid
         _pid=0;
     fi
@@ -129,7 +144,7 @@ get_pid_from_file() {
 # PID file and checking the PID it contains.  If the file does
 # not exist, the process is assumed to not be running.
 check_running() {
-    local proc_name=${1} # Process name.
+    local proc_name="${1}"  # Process name.
     # Initially mark the process as not running.
     _running=0
 
@@ -137,9 +152,7 @@ check_running() {
     get_pid_from_file "${proc_name}"
     if [ ${_pid} -gt 0 ]; then
         # Use ps to check if PID is alive
-        ps -p ${_pid} 1>/dev/null
-        retcode=$?
-        if [ $retcode -eq 0 ]; then
+        if ps -p ${_pid} 1>/dev/null; then
             # No error, so PID IS ALIVE
             _running=1
         fi
@@ -148,17 +161,15 @@ check_running() {
 
 # Sends a signal to a process based on its PID file
 send_signal() {
-    local sig=${1}        # Signal number
-    local proc_name=${2}  # Process name.
+    local sig="${1}"        # Signal number
+    local proc_name="${2}"  # Process name.
 
     get_pid_from_file "${proc_name}"
-    if [ ${_pid} -eq 0 ]; then
+    if [ "${_pid}" -eq 0 ]; then
         log_info "Skip sending signal ${sig} to process ${proc_name}: \
 process is not running"
     else
-        kill "-${sig}" "${_pid}"
-        retcode=$?
-        if [ $retcode -ne 0 ]; then
+        if ! kill "-${sig}" "${_pid}"; then
             log_error "Failed to send signal ${sig} to process ${proc_name}, PID {$_pid}."
         fi
     fi
@@ -167,21 +178,20 @@ process is not running"
 # Start the Kea process. Do not start the process if there is an instance
 # already running.
 start_server() {
-    binary_path=${1}   # Full path to the binary.
-    full_command=$*    # Binary and arguments.
+    binary_path=${1}    # Full path to the binary.
     # Extract the name of the binary from the path.
     local binary_name
     binary_name=$(basename -- "${binary_path}")
     # Use the binary name to check if the process is already running.
     check_running "${binary_name}"
     # If process is running, don't start another one. Just log a message.
-    if [ ${_running} -ne 0 ]; then
+    if [ "${_running}" -ne 0 ]; then
         log_info "${binary_name} appears to be running, see: \
 PID ${_pid}, PID file: ${_pid_file}."
     else
-        log_info "Starting ${full_command}"
+        log_info "Starting ${*}"
         # Start the process.
-        ${full_command} &
+        "${@}" &
     fi
 }
 
@@ -196,14 +206,11 @@ stop_server() {
     # Use the binary name to check if the process is already running.
     check_running "${binary_name}"
     # If process isn't running, don't start another one. Just log a message.
-    if [ ${_running} -eq 0 ]; then
+    if [ "${_running}" -eq 0 ]; then
         log_info "${binary_name} isn't running."
     else
         log_info "Stopping ${binary_name}..."
-
-        kill "-${sig}" "${_pid}"
-        retcode=$?
-        if [ $retcode -ne 0 ]; then
+        if ! kill "-${sig}" "${_pid}"; then
             log_error "Stop failed, could not send signal ${sig} \
 to process ${proc_name}, PID ${_pid}."
         fi
@@ -221,28 +228,24 @@ reload_server() {
     # Use the binary name to check if the process is already running.
     check_running "${binary_name}"
     # If process isn't running, don't start another one. Just log a message.
-    if [ ${_running} -eq 0 ]; then
+    if [ "${_running}" -eq 0 ]; then
         log_info "${binary_name} isn't running."
     else
         log_info "Reloading ${binary_name}..."
-        kill -${sig} ${_pid}
-        retcode=$?
-        if [ $retcode -ne 0 ]; then
+        if ! kill "-${sig}" "${_pid}"; then
             log_error "Reload failed, could not send signal ${sig} \
 to process ${proc_name}, PID ${_pid}."
         fi
     fi
 }
 
-# Print Kea daemon verison
+# Print Kea daemon version
 print_version() {
     name=${1}
     binary_path=${2}
 
     if [ -e "${binary_path}" ]; then
-        ver=$(${binary_path} -v)
-        retcode=$?
-        if [ $retcode -ne 0 ]; then
+        if ! ver=$(${binary_path} -v); then
             log_error "Error checking version of binary file: ${binary_path}"
         fi
     else
@@ -258,7 +261,7 @@ print_version() {
 # Check if the Kea configuration file location has been specified in the
 # keactrl configuration file. If not, it is a warning or a fatal error.
 check_kea_conf() {
-    local conf_file=${1} # Kea config file name.
+    local conf_file="${1-}"     # Kea config file name.
     if [ -z "${conf_file}" ]; then
         log_error "Configuration file for Kea not specified."
         exit 1
@@ -277,17 +280,17 @@ check_kea_conf() {
 #   and be set to yes, e.g. ${dhcp4} should be equal to yes if server name
 #   is dhcp4
 run_conditional() {
-    local server=${1}         # Server name: dhcp4, dhcp6, dhcp_ddns, ctrl_agent, netconf
-    local commands="${2}"     # Commands to execute
-    local check_file_cfg=${3} # Check if server enabled in the configuration file
-    local is_all=0            # is all servers or a specific one
+    local server="${1}"             # Server name: dhcp4, dhcp6, dhcp_ddns, ctrl_agent, netconf
+    local commands="${2}"           # Commands to execute
+    local check_file_cfg="${3}"     # Check if server enabled in the configuration file
+    local is_all=0                  # is all servers or a specific one
 
     # If keyword "all" is not on the list of servers we will have to check
     # if our specific server is on the list. If, not return.
     is_in_list "all" "${servers}"
-    if [ ${_inlist} -eq 0 ]; then
+    if [ "${_inlist}" -eq 0 ]; then
         is_in_list "${server}" "${servers}"
-        if [ ${_inlist} -eq 0 ]; then
+        if [ "${_inlist}" -eq 0 ]; then
             return
         fi
     else
@@ -298,12 +301,12 @@ run_conditional() {
 # Right now we're checking keactrl.in rather than keactrl directly. The have_netconf
 # variable is set by configure script (it's in keactrl and not in keactrl.in).
 # shellcheck disable=SC2154
-        if [ "${have_netconf}" -eq 0 ]; then
+        if ! ${have_netconf}; then
             return
         fi
         # reload is not supported for netconf.
         if [ "${command}" = "reload" ]; then
-            if [ ${is_all} -eq 1 ]; then
+            if [ "${is_all}" -eq 1 ]; then
                 return
             fi
             log_warning "netconf does not support reload"
@@ -331,12 +334,12 @@ run_conditional() {
 # Note that when the configuration is applied this location may be
 # altered and only the handful of initial messages will be logged
 # to the default file.
-if [ -z "${KEA_LOGGER_DESTINATION}" ]; then
-    prefix=@prefix@
-    export KEA_LOGGER_DESTINATION=@localstatedir@/log/kea.log
+if [ -z "${KEA_LOGGER_DESTINATION+x}" ]; then
+    prefix="@prefix@"
+    export KEA_LOGGER_DESTINATION="@localstatedir@/log/kea.log"
 fi
 
-command=${1}
+command=${1-}
 if [ -z "${command}" ]; then
     log_error "missing command"
     usage
@@ -350,31 +353,27 @@ if test "${command}" = "-v" || test "${command}" = "--version" ; then
 fi
 
 is_in_list "${command}" "start stop reload status version"
-if [ ${_inlist} -eq 0 ]; then
+if [ "${_inlist}" -eq 0 ]; then
     log_error "invalid command: ${command}"
     exit 1
 fi
 
 # Get the location of the keactrl configuration file.
-# Need to disable a false positive from shellcheck. Yes, prefix is used.
-# shellcheck disable=SC2034
-prefix=@prefix@
-# Avoid problem with localstatedir / runstatedir
-# shellcheck disable=SC2034
-localstatedir=@localstatedir@
-keactrl_conf=@sysconfdir@/@PACKAGE@/keactrl.conf
+prefix="@prefix@"
+localstatedir="@localstatedir@"
+keactrl_conf="@sysconfdir@/@PACKAGE@/keactrl.conf"
 
 servers="all"
 
 shift
-while [ -n "${1}" ]
+while test ${#} -gt 0
 do
     option=${1}
     case ${option} in
         # Override keactrl configuration file.
         -c|--ctrl-config)
             shift
-            keactrl_conf=${1}
+            keactrl_conf=${1-}
             if [ -z "${keactrl_conf}" ]; then
                 log_error "keactrl-config-file not specified"
                 usage
@@ -385,7 +384,7 @@ do
         # executed.
         -s|--server)
             shift
-            servers=$( printf "%s" "${1}" | tr "," "\n" )
+            servers=$(printf '%s' "${1-}" | tr ',' '\n')
             if [ -z "${servers}" ]; then
                 log_error "servers not specified"
                 usage
@@ -395,7 +394,7 @@ do
             for s in ${servers}
             do
                 is_in_list "${s}" "all dhcp4 dhcp6 dhcp_ddns ctrl_agent netconf"
-                if [ ${_inlist} -eq 0 ]; then
+                if [ "${_inlist}" -eq 0 ]; then
                     log_error "invalid server name: ${s}"
                     exit 1
                 fi
@@ -422,37 +421,38 @@ fi
 
 # Get location of the DHCPv4 server binary.
 # shellcheck disable=SC2154
-if [ -z "${dhcp4_srv}" ]; then
+if [ -z "${dhcp4_srv+x}" ]; then
     log_error "dhcp4_srv parameter not specified"
     exit 1
 fi
 
 # Get location of the DHCPv6 server binary.
 # shellcheck disable=SC2154
-if [ -z "${dhcp6_srv}" ]; then
+if [ -z "${dhcp6_srv+x}" ]; then
     log_error "dhcp6_srv parameter not specified"
     exit 1
 fi
 
 # Get location of the DHCP DDNS server binary.
 # shellcheck disable=SC2154
-if [ -z "${dhcp_ddns}" ]; then
+if [ -z "${dhcp_ddns+x}" ]; then
     log_error "dhcp_ddns parameter not specified"
     exit 1
 fi
 
 # Get location of the Control Agent binary.
 # shellcheck disable=SC2154
-if [ -z "${ctrl_agent_srv}" ]; then
+if [ -z "${ctrl_agent_srv+x}" ]; then
     log_error "ctrl_agent_srv parameter not specified"
     exit 1
 fi
 
 # Get location of the Netconf binary.
-# have_netconf is set by configure in keactrl, but shellcheck checks keactrl.in
-# shellcheck disable=SC2154
-if [ "${have_netconf}" -eq 1 ]; then
-    if [ -z "${netconf_srv}" ]; then
+if ${have_netconf}; then
+    # shellcheck disable=SC2154
+    # SC2154: netconf_srv is referenced but not assigned.
+    # reason: it is taken from keactrl.conf
+    if [ -z "${netconf_srv+x}" ]; then
         log_error "netconf_srv parameter not specified"
         exit 1
     fi
@@ -471,7 +471,6 @@ case ${command} in
     start)
         args=""
         # kea_verbose is set in keactrl.conf that shellcheck is unable to load.
-        # shellcheck disable=SC2154
         if [ "${kea_verbose}" = "yes" ]; then
             args="-d"
         fi
@@ -480,10 +479,8 @@ case ${command} in
         # and if they are enabled in the keactrl configuration file.
         # The variables (dhcp4_srv, dhcp6_serv, dhcp_ddns_srv etc) are set in the
         # keactrl.conf file that shellcheck is unable to read.
-        # shellcheck disable=SC2154
         run_conditional "dhcp4" "start_server ${dhcp4_srv} -c ${kea_dhcp4_config_file} ${args}" 1
         run_conditional "dhcp6" "start_server ${dhcp6_srv} -c ${kea_dhcp6_config_file} ${args}" 1
-        # shellcheck disable=SC2154
         run_conditional "dhcp_ddns" "start_server ${dhcp_ddns_srv} -c ${kea_dhcp_ddns_config_file} \
 ${args}" 1
         run_conditional "ctrl_agent" "start_server ${ctrl_agent_srv} -c ${kea_ctrl_agent_config_file} \
@@ -517,8 +514,8 @@ ${args}" 1
 
     status)
         if [ -t 1 ]; then
-            inactive="\e[91minactive\e[0m"
-            active="\e[92mactive\e[0m"
+            inactive="\033[91minactive\033[0m"
+            active="\033[92mactive\033[0m"
         else
             inactive="inactive"
             active="active"
@@ -529,33 +526,33 @@ ${args}" 1
         # correct. For details, see this fine explanation:
         # https://unix.stackexchange.com/questions/443989/whats-the-right-way-to-quote-command-arg
         check_running "$(basename -- "${dhcp4_srv}")"
-        if [ ${_running} -eq 1 ]; then
+        if [ "${_running}" -eq 1 ]; then
             kea4_status=$active
         fi
         printf "DHCPv4 server: %b\n" "${kea4_status}"
 
         kea6_status=$inactive
         check_running "$(basename -- "${dhcp6_srv}")"
-        if [ ${_running} -eq 1 ]; then
+        if [ "${_running}" -eq 1 ]; then
             kea6_status=$active
         fi
         printf "DHCPv6 server: %b\n" "${kea6_status}"
 
         d2_status=$inactive
         check_running "$(basename -- "${dhcp_ddns_srv}")"
-        if [ ${_running} -eq 1 ]; then
+        if [ "${_running}" -eq 1 ]; then
             d2_status="active"
         fi
         printf "DHCP DDNS: %b\n" "${d2_status}"
 
         agent_status=$inactive
         check_running "$(basename -- "${ctrl_agent_srv}")"
-        if [ ${_running} -eq 1 ]; then
+        if [ "${_running}" -eq 1 ]; then
             agent_status=$active
         fi
         printf "Control Agent: %b\n" "${agent_status}"
 
-        if [ "${have_netconf}" -eq 1 ]; then
+        if ${have_netconf}; then
             netconf_status=$inactive
             check_running "$(basename -- "${netconf_srv}")"
             if [ "${_running}" -eq 1 ]; then
@@ -568,7 +565,7 @@ ${args}" 1
         printf "Kea DHCPv6 configuration file: %s\n" "${kea_dhcp6_config_file}"
         printf "Kea DHCP DDNS configuration file: %s\n" "${kea_dhcp_ddns_config_file}"
         printf "Kea Control Agent configuration file: %s\n" "${kea_ctrl_agent_config_file}"
-        if [ "${have_netconf}" -eq 1 ]; then
+        if ${have_netconf}; then
             printf "Kea Netconf configuration file: %s\n" "${kea_netconf_config_file}"
         fi
         printf "keactrl configuration file: %s\n" "${keactrl_conf}"
@@ -577,7 +574,7 @@ ${args}" 1
         check_kea_conf "${kea_dhcp6_config_file}"
         check_kea_conf "${kea_dhcp_ddns_config_file}"
         check_kea_conf "${kea_ctrl_agent_config_file}"
-        if [ "${have_netconf}" -eq 1 ]; then
+        if ${have_netconf}; then
             check_kea_conf "${kea_netconf_config_file}"
         fi
 
diff --git a/src/lib/log/tests/destination_test.sh.in b/src/lib/log/tests/destination_test.sh.in
--- a/src/lib/log/tests/destination_test.sh.in
+++ b/src/lib/log/tests/destination_test.sh.in
@@ -1,5 +1,6 @@
 #!/bin/sh
-# Copyright (C) 2011-2016 Internet Systems Consortium, Inc. ("ISC")
+
+# Copyright (C) 2011-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
@@ -7,26 +8,23 @@
 
 # Checks that the logger will route messages to the chosen destination.
 
-testname="Destination test"
-echo $testname
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
 
-failcount=0
-tempfile=@abs_builddir@/destination_test_tempfile_$$
-destfile1_tmp=@abs_builddir@/destination_test_destfile_1_tmp_$$
-destfile2_tmp=@abs_builddir@/destination_test_destfile_2_tmp_$$
-destfile1=@abs_builddir@/destination_test_destfile_1_$$
-destfile2=@abs_builddir@/destination_test_destfile_2_$$
+# Include common test library.
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+. "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
 
-passfail() {
-    if [ $1 -eq 0 ]; then
-        echo " pass"
-    else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
-    fi
-}
+tempfile="@abs_builddir@/destination_test_tempfile_$$"
+destfile1_tmp="@abs_builddir@/destination_test_destfile_1_tmp_$$"
+destfile2_tmp="@abs_builddir@/destination_test_destfile_2_tmp_$$"
+destfile1="@abs_builddir@/destination_test_destfile_1_$$"
+destfile2="@abs_builddir@/destination_test_destfile_2_$$"
 
-echo "1. One logger, multiple destinations:"
+printf '1. One logger, multiple destinations:\n'
+
 cat > $tempfile << .
 FATAL [example] LOG_WRITE_ERROR error writing to test1: 42
 ERROR [example] LOG_READING_LOCAL_FILE reading local message file dummy/file
@@ -36,32 +34,34 @@ ERROR [example.beta] LOG_BAD_DESTINATION unrecognized log destination: beta_erro
 rm -f $destfile1 $destfile2
 ./logger_example -s error -f $destfile1_tmp -f $destfile2_tmp
 
-# strip the pids
-sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\]/[\1]/' < $destfile1_tmp > $destfile1
-sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\]/[\1]/' < $destfile2_tmp > $destfile2
+# strip the pids and thread ids
+sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1,\}\)\]/[\1]/' < $destfile1_tmp > $destfile1
+sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1,\}\)\]/[\1]/' < $destfile2_tmp > $destfile2
+# strip the thread ids
 
-echo -n  "   - destination 1:"
+test_start 'logger-destination.one-logger-file-1'
 cut -d' ' -f3- $destfile1 | diff $tempfile -
-passfail $?
+test_finish $?
 
-echo -n  "   - destination 2:"
+test_start 'logger-destination.one-logger-file-2'
 cut -d' ' -f3- $destfile2 | diff $tempfile -
-passfail $?
+test_finish $?
 
 # Tidy up.
 rm -f $tempfile $destfile1_tmp $destfile2_tmp $destfile1 $destfile2
 
-echo     "2. Two loggers, different destinations and severities"
+printf '2. Two loggers, different destinations and severities:\n'
 rm -f $destfile1 $destfile2
 ./logger_example -l example -s info -f $destfile1_tmp -l alpha -s warn -f $destfile2_tmp
 
-# strip the pids
-sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\]/[\1]/' < $destfile1_tmp > $destfile1
-sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\]/[\1]/' < $destfile2_tmp > $destfile2
+# strip the pids and thread ids
+sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1,\}\)\]/[\1]/' < $destfile1_tmp > $destfile1
+sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1,\}\)\]/[\1]/' < $destfile2_tmp > $destfile2
 
 # All output for example and example.beta should have gone to destfile1.
 # Output for example.alpha should have done to destfile2.
 
+test_start 'logger-destination.multiples-loggers-file-1'
 cat > $tempfile << .
 FATAL [example] LOG_WRITE_ERROR error writing to test1: 42
 ERROR [example] LOG_READING_LOCAL_FILE reading local message file dummy/file
@@ -71,26 +71,15 @@ ERROR [example.beta] LOG_BAD_DESTINATION unrecognized log destination: beta_erro
 WARN  [example.beta] LOG_BAD_STREAM bad log console output stream: beta_warn
 INFO  [example.beta] LOG_READ_ERROR error reading from message file beta: info
 .
-echo -n  "   - destination 1:"
 cut -d' ' -f3- $destfile1 | diff $tempfile -
-passfail $?
+test_finish $?
 
-echo -n  "   - destination 2:"
+test_start 'logger-destination.multiples-loggers-file-2'
 cat > $tempfile << .
 WARN  [example.alpha] LOG_READ_ERROR error reading from message file a.txt: dummy reason
 .
 cut -d' ' -f3- $destfile2 | diff $tempfile -
-passfail $?
-
-if [ $failcount -eq 0 ]; then
-    echo "PASS: $testname"
-elif [ $failcount -eq 1 ]; then
-    echo "FAIL: $testname - 1 test failed"
-else
-    echo "FAIL: $testname - $failcount tests failed"
-fi
+test_finish $?
 
 # Tidy up.
 rm -f $tempfile $destfile1_tmp $destfile2_tmp $destfile1 $destfile2
-
-exit $failcount
diff --git a/src/share/database/scripts/cql/upgrade_2.0_to_3.0.sh.in b/src/share/database/scripts/cql/upgrade_2.0_to_3.0.sh.in
--- a/src/share/database/scripts/cql/upgrade_2.0_to_3.0.sh.in
+++ b/src/share/database/scripts/cql/upgrade_2.0_to_3.0.sh.in
@@ -1,12 +1,31 @@
 #!/bin/sh
 
-prefix=@prefix@
+# Copyright (C) 2018-2021 Internet Systems Consortium, Inc. ("ISC")
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, 'local' is undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+prefix="@prefix@"
+
 # Include utilities. Use installed version if available and
 # use build version if it isn't.
 if [ -e "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh" ]; then
-    . @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh
+    . "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh"
 else
-    . @abs_top_builddir@/src/bin/admin/admin-utils.sh
+    . "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 fi
 
 # Need a path for temporary files created during upgrade data migration
@@ -18,11 +37,9 @@ else
     temp_file_dir="@abs_top_builddir@/src/share/database/scripts/cql"
 fi
 
-cqlargs=$@
-
 # Ensures the current schema version is 2.0. If not it exits.
 check_version() {
-    version=$(cql_version $cqlargs)
+    version=$(cql_version "${@}")
 
     if [ "${version}" != "2.0" ]; then
         printf "This script upgrades 2.0 to 3.0. Reported version is %s. Skipping upgrade.\n" "${version}"
@@ -32,7 +49,7 @@ check_version() {
 
 # Peforms the schema changes from 2.0 to 3.0
 update_schema() {
-    cqlsh $cqlargs <<EOF
+    cqlsh "${@}" <<EOF
 -- This line starts database upgrade to version 3.0
 
 -- Add a column holding leases for user context.
@@ -61,25 +78,19 @@ INSERT INTO schema_version (version, minor) VALUES(3, 0);
 
 -- This line concludes database upgrade to version 3.0
 EOF
-
-    if [ "$?" -ne 0 ]
-    then
-        echo Schema udpate FAILED!
-        exit 1
-    fi
 }
 
 # Function to delete temporary migration files
 clean_up() {
     # clean up the files
-    if [ -e "$export_file" ]
+    if [ -e "${export_file}" ]
     then
-        rm $export_file
+        rm "${export_file}"
     fi
 
-    if [ -e "$update_file" ]
+    if [ -e "${update_file}" ]
     then
-        rm $update_file
+        rm "${update_file}"
     fi
 }
 
@@ -102,7 +113,7 @@ exit_now() {
         echo "Data Migration FAILURE! $explanation"
     fi
 
-    exit $status
+    exit "${status}"
 }
 
 # Function adds a column to the global, $update_cols if needed
@@ -131,7 +142,7 @@ check_column() {
     if [ "$val" = "$old_id" ]
     then
         # If the accumulator isn't empty, we need a comma
-        if [ ! -z "$update_cols" ]
+        if [ -n "${update_cols}" ]
         then
             comma=","
         fi
@@ -156,7 +167,7 @@ check_column() {
 # for each row that needs at least one of the columns updated. In other
 # words, if at least one of the subnet ID columns in a row is 0, an
 # update statement for that row will be emitted.  The update statements
-# are captured in a second temprory file, the "update" file.
+# are captured in a second temporary file, the "update" file.
 #
 # After exhausting the export file, the update file is submitted to
 # cqlsh for execution.
@@ -174,8 +185,7 @@ migrate_host_data() {
         (id, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id)\
         TO '$export_file'"
 
-    cqlsh $cqlargs -e "$query"
-    if [ "$?" -ne 0 ]
+    if ! cqlsh "${@}" -e "$query"
     then
         exit_now 1 "Cassandra export failed! Could not migrate data!"
     fi
@@ -183,7 +193,7 @@ migrate_host_data() {
     # Strip the carriage returns that CQL insists on adding.
     if [ -e "$export_file" ]
     then
-        cat $export_file | tr -d '\015' > $export_file.2
+        tr -d '\015' < "${export_file}" > "${export_file}.2"
         mv $export_file.2 $export_file
     else
         # Shouldn't happen but then again we're talking about CQL here
@@ -193,14 +203,16 @@ migrate_host_data() {
     # Iterate through the exported data, accumulating update statements,
     # one for each reservation that needs updating.  We should have one
     # host per line.
-    line_cnt=0;
-    update_cnt=0;
+    line_cnt=0
+    update_cnt=0
 
     while read -r line
     do
         line_cnt=$((line_cnt + 1));
         update_cols=""
         xIFS="$IFS"
+        # shellcheck disable=SC3003
+        # SC3003: In POSIX sh, $'..' is undefined.
         IFS=$','
 
         i=1
@@ -212,13 +224,13 @@ migrate_host_data() {
                 host_id="$val"
                 ;;
             2)
-                check_column $val host_ipv4_subnet_id
+                check_column "$val" host_ipv4_subnet_id
                 ;;
             3)
-                check_column $val host_ipv6_subnet_id
+                check_column "$val" host_ipv6_subnet_id
                 ;;
             4)
-                check_column $val option_subnet_id
+                check_column "$val" option_subnet_id
                 ;;
             *)
                 # We're going to assume that since any error is fatal
@@ -235,14 +247,14 @@ migrate_host_data() {
         fi
 
         # If any of the current host's columns need to be replace, append an update for it
-        if [ ! -z "$update_cols" ]
+        if [ -n "$update_cols" ]
         then
             echo "update host_reservations set $update_cols where id = $host_id;" >> $update_file
             update_cnt=$((update_cnt + 1))
         fi
 
         IFS="$xIFS"
-    done <  $export_file
+    done < "${export_file}"
 
     # If we didn't record any updates, then hey, we're good to go!
     if [ "$update_cnt" -eq 0 ]
@@ -253,8 +265,7 @@ migrate_host_data() {
     # We have at least one update in the update file, so submit it # to cqlsh.
     echo "$update_cnt update statements written to $update_file"
     echo "Running the updates..."
-    cqlsh $cqlargs -f "$update_file"
-    if [ "$?" -ne 0 ]
+    if ! cqlsh "${@}" -f "$update_file"
     then
         exit_now 1 "Cassandra updates failed"
     fi
@@ -262,6 +273,9 @@ migrate_host_data() {
     exit_now 0 "Updated $update_cnt of $line_cnt records"
 }
 
-check_version
-update_schema
-migrate_host_data
+check_version "${@}"
+if ! update_schema "${@}"; then
+    printf 'Schema update FAILED!\n'
+    exit 1
+fi
+migrate_host_data "${@}"
diff --git a/tools/cql_config b/tools/cql_config
--- a/tools/cql_config
+++ b/tools/cql_config
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2016-2020 Internet Systems Consortium, Inc. ("ISC")
+# Copyright (C) 2016-2021 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
@@ -9,6 +9,10 @@
 # This is keactrl script responsible for starting up Kea processes.
 # This script is used to run Kea from installation directory,
 # as well as for running tests.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
 
 cql_lib="cassandra"
 
@@ -23,9 +27,9 @@ if ! [ -f "${DIR}/cql_config_defines.sh" ] || ! [ -x "${DIR}/cql_config_defines.
     exit 1
 fi
 
-# Shellcheck tries to follow this link and gets confused about not being able
-# to find the file.
-# shellcheck disable=SC1090
+# shellcheck disable=SC1091
+# SC1091: Not following: ./cql_config_defines.sh was not specified as input (see shellcheck -x).
+# shellcheck source=./tools/cql_config_defines.sh.sample
 . "${DIR}/cql_config_defines.sh"
 
 if [ $# -ne 1 ] && [ $# -ne 2 ]; then
