New upstream version 2.3.6

diff --git a/src/bin/admin/tests/mysql_tests.sh.in b/src/bin/admin/tests/mysql_tests.sh.in
--- a/src/bin/admin/tests/mysql_tests.sh.in
+++ b/src/bin/admin/tests/mysql_tests.sh.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2014-2022 Internet Systems Consortium, Inc. ("ISC")
+# Copyright (C) 2014-2023 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
@@ -21,7 +21,7 @@ set -eu
 . "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
 
 # Include admin utilities
-. "@abs_top_srcdir@/src/bin/admin/admin-utils.sh"
+. "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 
 # Set path to the production schema scripts
 db_scripts_dir="@abs_top_srcdir@/src/share/database/scripts"
@@ -63,7 +63,6 @@ run_statement() {
         assert_str_eq "$exp_value" "$value" "$hdr: SQL=[$qry] wrong: (expected value %s, returned %s)"
     fi
 }
-
 
 # Wipe all tables from the DB:
 mysql_wipe() {
@@ -158,7 +157,7 @@ INSERT INTO schema_version VALUES (1, 7);'
 }
 
 mysql_db_version_with_extra_test() {
-    test_start "mysql.db-version-with-extra"
+    test_start "mysql.db-version_with_extra"
 
     # Let's wipe the whole database
     mysql_wipe
@@ -189,13 +188,13 @@ INSERT INTO schema_version VALUES (1, 7);'
     # Multiple -x.
     run_command \
         "${kea_admin}" db-version mysql -u "${db_user}" -p "${db_password}" -n "${db_name}" \
-        -x --protocol=TCP -x --hello 2> "@abs_top_srcdir@/src/bin/admin/test-data"
+        -x --protocol=TCP -x --hello 2> "@abs_top_builddir@/src/bin/admin/test-data"
     assert_eq 2 "${EXIT_CODE}" "kea-admin -x -x succeeded. (expected %d, exit code %d)"
-    if ! grep -F "unknown option '--hello'" "@abs_top_srcdir@/src/bin/admin/test-data"; then
+    if ! grep -F "unknown option '--hello'" "@abs_top_builddir@/src/bin/admin/test-data"; then
         printf 'second parameter --hello was not passed to mysql with -x\n'
         test_finish 1
     fi
-    rm -f "@abs_top_srcdir@/src/bin/admin/test-data"
+    rm -f "@abs_top_builddir@/src/bin/admin/test-data"
 
     # Let's wipe the whole database
     mysql_wipe
@@ -268,20 +267,35 @@ mysql_host_reservation_init_test() {
 mysql_upgrade_schema_to_version() {
     target_version=$1
 
+    upgrade_scripts_dir=${db_scripts_dir}/mysql
+
     # Check if the scripts directory exists at all.
-    if [ ! -d ${db_scripts_dir}/mysql ]; then
-        log_error "Invalid scripts directory: ${db_scripts_dir}/mysql"
+    if [ ! -d ${upgrade_scripts_dir} ]; then
+        log_error "Invalid scripts directory: ${upgrade_scripts_dir}"
         exit 1
     fi
 
     # Check if there are any files in it
-    num_files=$(find ${db_scripts_dir}/mysql/upgrade*.sh -type f | wc -l)
+    num_files=$(find ${upgrade_scripts_dir} -name 'upgrade*.sh' -type f | wc -l)
     if [ "${num_files}" -eq 0 ]; then
-        log_error "No scripts in ${db_scripts_dir}/mysql?"
+        upgrade_scripts_dir=@abs_top_builddir@/src/share/database/scripts/mysql
+
+        # Check if the scripts directory exists at all.
+        if [ ! -d ${upgrade_scripts_dir} ]; then
+            log_error "Invalid scripts directory: ${upgrade_scripts_dir}"
+            exit 1
+        fi
+
+        # Check if there are any files in it
+        num_files=$(find "${upgrade_scripts_dir}" -name 'upgrade*.sh' -type f | wc -l)
+    fi
+
+    if [ "${num_files}" -eq 0 ]; then
+        log_error "No scripts in ${upgrade_scripts_dir}?"
         exit 1
     fi
 
-    for script in "${db_scripts_dir}"/mysql/upgrade*.sh
+    for script in "${upgrade_scripts_dir}"/upgrade*.sh
     do
         version=$(mysql_version)
         if [ "${version}" = "${target_version}" ]
@@ -673,6 +687,34 @@ mysql_upgrade_13_to_14_test() {
     done
 }
 
+mysql_upgrade_14_to_15_test() {
+    # table: dhcp4_options new cancelled column.
+    qry="select cancelled from dhcp4_options"
+    run_statement "dhcp4_options" "$qry"
+
+    # table: dhcp6_options new cancelled column.
+    qry="select cancelled from dhcp6_options"
+    run_statement "dhcp6_options" "$qry"
+
+    # Check if offer_lifetime was added to dhcp4_shared_network table.
+    qry="SELECT offer_lifetime from dhcp4_shared_network limit 1;"
+    run_command \
+        mysql_execute "${qry}"
+    assert_eq 0 "${EXIT_CODE}" "${qry}. (expected status code %d, returned %d)"
+
+    # Check if offer_lifetime was added to dhcp4_subnet table.
+    qry="SELECT offer_lifetime from dhcp4_subnet limit 1;"
+    run_command \
+        mysql_execute "${qry}"
+    assert_eq 0 "${EXIT_CODE}" "${qry}. (expected status code %d, returned %d)"
+
+    # Check if offer_lifetime was added to dhcp4_client_class table.
+    qry="SELECT offer_lifetime from dhcp4_client_class limit 1;"
+    run_command \
+        mysql_execute "${qry}"
+    assert_eq 0 "${EXIT_CODE}" "${qry}. (expected status code %d, returned %d)"
+}
+
 mysql_upgrade_test() {
 
     test_start "mysql.upgrade"
@@ -694,7 +736,7 @@ mysql_upgrade_test() {
 
     # Verify that the upgraded schema reports the latest version.
     version=$("${kea_admin}" db-version mysql -u "${db_user}" -p "${db_password}" -n "${db_name}" -d "${db_scripts_dir}")
-    assert_str_eq "14.0" "${version}" "Expected kea-admin to return %s, returned value was %s"
+    assert_str_eq "15.0" "${version}" "Expected kea-admin to return %s, returned value was %s"
 
     # Let's check that the new tables are indeed there.
 
@@ -1321,6 +1363,9 @@ SET @disable_audit = 0;"
     # Check upgrade from 13.0 to 14.0.
     mysql_upgrade_13_to_14_test
 
+    # Check upgrade from 14.0 to 15.0.
+    mysql_upgrade_14_to_15_test
+
     # Let's wipe the whole database
     mysql_wipe
 
@@ -1344,7 +1389,7 @@ mysql_lease4_dump_test() {
              "${output_file}.tmp" \
              "/tmp/$(basename "${output_file}").tmp" \
     ; do
-        if printf '%s' "${@}" | grep 'y' > /dev/null; then
+        if printf '%s' "$@" | grep 'y' > /dev/null; then
             touch "${i}"
         else
             rm -f "${i}"
@@ -1373,7 +1418,7 @@ insert into lease4 values(12,22,NULL,40,(SELECT FROM_UNIXTIME(1643212345)),50,1,
     # Dump lease4 to output_file
     run_command \
         "${kea_admin}" lease-dump mysql -4 -u "${db_user}" -p "${db_password}" -n "${db_name}" \
-            -d "${db_scripts_dir}" -o "${output_file}" "${@}"
+            -d "${db_scripts_dir}" -o "${output_file}" "$@"
     assert_eq 0 "${EXIT_CODE}" "kea-admin lease-dump -4 failed, expected exit code %d, actual %d"
 
     # Compare the dump output to reference file, they should be identical
@@ -1381,8 +1426,9 @@ insert into lease4 values(12,22,NULL,40,(SELECT FROM_UNIXTIME(1643212345)),50,1,
         cmp -s "${output_file}" "${ref_file}"
     assert_eq 0 "${EXIT_CODE}" "dump file does not match reference file, expected exit code %d, actual %d, diff:\n$(diff ${ref_file} ${output_file})"
 
-    # Remove the output file.
+    # Remove the files.
     rm -f "${output_file}"
+    rm -f "${output_file}.tmp"
 
     # Let's wipe the whole database
     mysql_wipe
@@ -1407,7 +1453,7 @@ mysql_lease6_dump_test() {
              "${output_file}.tmp" \
              "/tmp/$(basename "${output_file}").tmp" \
     ; do
-        if printf '%s' "${@}" | grep 'y' > /dev/null; then
+        if printf '%s' "$@" | grep 'y' > /dev/null; then
             touch "${i}"
         else
             rm -f "${i}"
@@ -1435,7 +1481,7 @@ insert into lease6 values('::12',22,30,(SELECT FROM_UNIXTIME(1643212345)),40,50,
     # Dump lease4 to output_file
     run_command \
         "${kea_admin}" lease-dump mysql -6 -u "${db_user}" -p "${db_password}" -n "${db_name}" \
-            -d "${db_scripts_dir}" -o "${output_file}" "${@}"
+            -d "${db_scripts_dir}" -o "${output_file}" "$@"
     assert_eq 0 "${EXIT_CODE}" "kea-admin lease-dump -6 failed, expected exit code %d, actual %d"
 
     # Compare the dump output to reference file, they should be identical
@@ -1443,8 +1489,9 @@ insert into lease6 values('::12',22,30,(SELECT FROM_UNIXTIME(1643212345)),40,50,
         cmp -s "${output_file}" "${ref_file}"
     assert_eq 0 "${EXIT_CODE}" "dump file does not match reference file, expected exit code %d, actual %d, diff:\n$(diff ${ref_file} ${output_file})"
 
-    # Remove the output file.
+    # Remove the files.
     rm -f "${output_file}"
+    rm -f "${output_file}.tmp"
 
     # Let's wipe the whole database
     mysql_wipe
@@ -1457,7 +1504,14 @@ mysql_lease4_upload_test() {
     test_start "mysql.lease4_upload_test${1-}"
 
     input_file="@abs_top_srcdir@/src/bin/admin/tests/data/lease4_dump_test.reference.csv"
-    output_file="@abs_top_srcdir@/src/bin/admin/tests/data/lease4_dump_test.output.csv"
+    input_file_cp="@abs_top_builddir@/src/bin/admin/tests/data/lease4_dump_test.reference.csv"
+    output_file="@abs_top_builddir@/src/bin/admin/tests/data/lease4_dump_test.output.csv"
+
+    if [ "${input_file}" != "${input_file_cp}" ]; then
+        cp -f ${input_file} ${input_file_cp}
+        input_file=${input_file_cp}
+        input_file_cp=""
+    fi
 
     # Wipe the whole database.
     mysql_wipe
@@ -1470,7 +1524,7 @@ mysql_lease4_upload_test() {
              "${output_file}.tmp" \
              "/tmp/$(basename "${input_file}").tmp" \
     ; do
-        if printf '%s' "${@}" | grep 'y' > /dev/null; then
+        if printf '%s' "$@" | grep 'y' > /dev/null; then
             touch "${i}"
         else
             rm -f "${i}"
@@ -1487,14 +1541,14 @@ mysql_lease4_upload_test() {
     run_command \
         "${kea_admin}" lease-upload mysql -4 -u "${db_user}" \
             -p "${db_password}" -n "${db_name}" -d "${db_scripts_dir}" \
-            -i "${input_file}" "${@}"
+            -i "${input_file}" "$@"
     assert_eq 0 "${EXIT_CODE}" "kea-admin lease-upload -4 failed, expected exit code %d, actual %d"
 
     # Dump leases.
     run_command \
         "${kea_admin}" lease-dump mysql -4 -u "${db_user}" \
             -p "${db_password}" -n "${db_name}" -d "${db_scripts_dir}" \
-            -o "${output_file}" "${@}"
+            -o "${output_file}" "$@"
     assert_eq 0 "${EXIT_CODE}" "kea-admin lease-dump -4 failed, expected exit code %d, actual %d"
 
     # Compare the initial file used for upload to the file retrieved from dump, they should be identical.
@@ -1502,8 +1556,13 @@ mysql_lease4_upload_test() {
         cmp -s "${input_file}" "${output_file}"
     assert_eq 0 "${EXIT_CODE}" "file resulted from dump after upload does not match file used for upload, expected exit code %d, actual %d, diff:\n$(diff ${input_file} ${output_file})"
 
-    # Remove the output file.
+    # Remove the files.
+    if [ "${input_file}" != "${input_file_cp}" ]; then
+        rm -f "${input_file}"
+    fi
+    rm -f "${input_file}.tmp"
     rm -f "${output_file}"
+    rm -f "${output_file}.tmp"
 
     # Wipe the whole database.
     mysql_wipe
@@ -1516,7 +1575,14 @@ mysql_lease6_upload_test() {
     test_start "mysql.lease6_upload_test${1-}"
 
     input_file="@abs_top_srcdir@/src/bin/admin/tests/data/lease6_dump_test.reference.csv"
-    output_file="@abs_top_srcdir@/src/bin/admin/tests/data/lease6_dump_test.output.csv"
+    input_file_cp="@abs_top_builddir@/src/bin/admin/tests/data/lease6_dump_test.reference.csv"
+    output_file="@abs_top_builddir@/src/bin/admin/tests/data/lease6_dump_test.output.csv"
+
+    if [ "${input_file}" != "${input_file_cp}" ]; then
+        cp -f ${input_file} ${input_file_cp}
+        input_file=${input_file_cp}
+        input_file_cp=""
+    fi
 
     # Wipe the whole database.
     mysql_wipe
@@ -1529,7 +1595,7 @@ mysql_lease6_upload_test() {
              "${output_file}.tmp" \
              "/tmp/$(basename "${input_file}").tmp" \
     ; do
-        if printf '%s' "${@}" | grep 'y' > /dev/null; then
+        if printf '%s' "$@" | grep 'y' > /dev/null; then
             touch "${i}"
         else
             rm -f "${i}"
@@ -1546,14 +1612,14 @@ mysql_lease6_upload_test() {
     run_command \
         "${kea_admin}" lease-upload mysql -6 -u "${db_user}" \
             -p "${db_password}" -n "${db_name}" -d "${db_scripts_dir}" \
-            -i "${input_file}" "${@}"
+            -i "${input_file}" "$@"
     assert_eq 0 "${EXIT_CODE}" "kea-admin lease-upload -6 failed, expected exit code %d, actual %d"
 
     # Dump leases.
     run_command \
         "${kea_admin}" lease-dump mysql -6 -u "${db_user}" \
             -p "${db_password}" -n "${db_name}" -d "${db_scripts_dir}" \
-            -o "${output_file}" "${@}"
+            -o "${output_file}" "$@"
     assert_eq 0 "${EXIT_CODE}" "kea-admin lease-dump -6 failed, expected exit code %d, actual %d"
 
     # Compare the initial file used for upload to the file retrieved from dump, they should be identical.
@@ -1561,8 +1627,13 @@ mysql_lease6_upload_test() {
         cmp -s "${input_file}" "${output_file}"
     assert_eq 0 "${EXIT_CODE}" "file resulted from dump after upload does not match file used for upload, expected exit code %d, actual %d, diff:\n$(diff ${input_file} ${output_file})"
 
-    # Remove the output file.
+    # Remove the files.
+    if [ "${input_file}" != "${input_file_cp}" ]; then
+        rm -f "${input_file}"
+    fi
+    rm -f "${input_file}.tmp"
     rm -f "${output_file}"
+    rm -f "${output_file}.tmp"
 
     # Wipe the whole database.
     mysql_wipe
@@ -2359,8 +2430,8 @@ mysql_lease4_upload_test
 mysql_lease4_upload_test -y
 mysql_lease6_upload_test
 mysql_lease6_upload_test -y
-mysql_lease6_stat_test
 mysql_lease4_stat_test
+mysql_lease6_stat_test
 mysql_lease_stat_upgrade_test
 mysql_lease_stat_recount_test
 mysql_unused_subnet_id_test
